LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name  | Type                  | Params | Mode
--------------------------------------------------------
0 | model | TransformerWithLMHead | 51.9 M | train
--------------------------------------------------------
51.9 M    Trainable params
0         Non-trainable params
51.9 M    Total params
207.792   Total estimated model params size (MB)
120       Modules in train mode
0         Modules in eval mode
Epoch 0:   0%|                    | 20/9109 [00:12<1:36:11,  1.57it/s, v_num=w2u8, train/loss=10.00]
Traceback (most recent call last):
  File "/home/matteo/Ricerca/miei_progetti/matformer/train_model.py", line 108, in <module>
    main()
    ~~~~^^
  File "/home/matteo/Ricerca/miei_progetti/matformer/train_model.py", line 105, in main
    trainer.fit(model, data)
    ~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/matteo/envs/torch-cuda/lib/python3.13/site-packages/pytorch_lightning/trainer/trainer.py", line 561, in fit
    call._call_and_handle_interrupt(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/matteo/envs/torch-cuda/lib/python3.13/site-packages/pytorch_lightning/trainer/call.py", line 48, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/matteo/envs/torch-cuda/lib/python3.13/site-packages/pytorch_lightning/trainer/trainer.py", line 599, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matteo/envs/torch-cuda/lib/python3.13/site-packages/pytorch_lightning/trainer/trainer.py", line 1012, in _run
    results = self._run_stage()
  File "/home/matteo/envs/torch-cuda/lib/python3.13/site-packages/pytorch_lightning/trainer/trainer.py", line 1056, in _run_stage
    self.fit_loop.run()
    ~~~~~~~~~~~~~~~~~^^
  File "/home/matteo/envs/torch-cuda/lib/python3.13/site-packages/pytorch_lightning/loops/fit_loop.py", line 216, in run
    self.advance()
    ~~~~~~~~~~~~^^
  File "/home/matteo/envs/torch-cuda/lib/python3.13/site-packages/pytorch_lightning/loops/fit_loop.py", line 455, in advance
    self.epoch_loop.run(self._data_fetcher)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/home/matteo/envs/torch-cuda/lib/python3.13/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 150, in run
    self.advance(data_fetcher)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/home/matteo/envs/torch-cuda/lib/python3.13/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 282, in advance
    batch, _, __ = next(data_fetcher)
                   ~~~~^^^^^^^^^^^^^^
  File "/home/matteo/envs/torch-cuda/lib/python3.13/site-packages/pytorch_lightning/loops/fetchers.py", line 134, in __next__
    batch = super().__next__()
  File "/home/matteo/envs/torch-cuda/lib/python3.13/site-packages/pytorch_lightning/loops/fetchers.py", line 61, in __next__
    batch = next(self.iterator)
  File "/home/matteo/envs/torch-cuda/lib/python3.13/site-packages/pytorch_lightning/utilities/combined_loader.py", line 341, in __next__
    out = next(self._iterator)
  File "/home/matteo/envs/torch-cuda/lib/python3.13/site-packages/pytorch_lightning/utilities/combined_loader.py", line 78, in __next__
    out[i] = next(self.iterators[i])
             ~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/matteo/envs/torch-cuda/lib/python3.13/site-packages/torch/utils/data/dataloader.py", line 708, in __next__
    data = self._next_data()
  File "/home/matteo/envs/torch-cuda/lib/python3.13/site-packages/torch/utils/data/dataloader.py", line 1455, in _next_data
    return self._process_data(data)
           ~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/matteo/envs/torch-cuda/lib/python3.13/site-packages/torch/utils/data/dataloader.py", line 1505, in _process_data
    data.reraise()
    ~~~~~~~~~~~~^^
  File "/home/matteo/envs/torch-cuda/lib/python3.13/site-packages/torch/_utils.py", line 733, in reraise
    raise exception
OSError: Caught OSError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/matteo/envs/torch-cuda/lib/python3.13/site-packages/torch/utils/data/_utils/worker.py", line 349, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/home/matteo/envs/torch-cuda/lib/python3.13/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/home/matteo/envs/torch-cuda/lib/python3.13/site-packages/torch_atlas_ds/atlas.py", line 339, in __getitem__
    return self.shards[shard_idx][within_shard_index]
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/home/matteo/envs/torch-cuda/lib/python3.13/site-packages/torch_atlas_ds/atlas.py", line 211, in __getitem__
    self._lazy_init()
    ~~~~~~~~~~~~~~~^^
  File "/home/matteo/envs/torch-cuda/lib/python3.13/site-packages/torch_atlas_ds/atlas.py", line 173, in _lazy_init
    self.block_index = np.load(self.root / 'index.npy', mmap_mode='r' if self.mmap_index else None)
                       ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matteo/envs/torch-cuda/lib/python3.13/site-packages/numpy/lib/_npyio_impl.py", line 480, in load
    return format.open_memmap(file, mode=mmap_mode,
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
                              max_header_size=max_header_size)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matteo/envs/torch-cuda/lib/python3.13/site-packages/numpy/lib/_format_impl.py", line 971, in open_memmap
    with open(os.fspath(filename), 'rb') as fp:
         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 24] Too many open files: '../matformer_norepo/liberliber_1024_tokens/3595/index.npy'

Exception ignored in atexit callback <function _start_and_connect_service.<locals>.teardown_atexit at 0x7f0feaa4b380>:
Traceback (most recent call last):
  File "/home/matteo/envs/torch-cuda/lib/python3.13/site-packages/wandb/sdk/lib/service_connection.py", line 94, in teardown_atexit
    conn.teardown(hooks.exit_code)
  File "/home/matteo/envs/torch-cuda/lib/python3.13/site-packages/wandb/sdk/lib/service_connection.py", line 226, in teardown
    self._router.join()
  File "/home/matteo/envs/torch-cuda/lib/python3.13/site-packages/wandb/sdk/interface/router.py", line 75, in join
    self._thread.join()
  File "/usr/lib/python3.13/threading.py", line 1094, in join
    self._handle.join(timeout)
KeyboardInterrupt:
