LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name  | Type                  | Params | Mode
--------------------------------------------------------
0 | model | TransformerWithLMHead | 58.2 M | train
--------------------------------------------------------
58.2 M    Trainable params
0         Non-trainable params
58.2 M    Total params
232.899   Total estimated model params size (MB)
164       Modules in train mode
0         Modules in eval mode
Epoch 0:   0%|                   | 40/33423 [00:25<6:00:23,  1.54it/s, v_num=9pcu, train/loss=2.260]
Traceback (most recent call last):
  File "/home/matteo/Ricerca/matformer/train_model.py", line 108, in <module>
    main()
  File "/home/matteo/Ricerca/matformer/train_model.py", line 105, in main
    trainer.fit(model, data)
  File "/home/matteo/torchcuda/lib/python3.12/site-packages/pytorch_lightning/trainer/trainer.py", line 561, in fit
    call._call_and_handle_interrupt(
  File "/home/matteo/torchcuda/lib/python3.12/site-packages/pytorch_lightning/trainer/call.py", line 48, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matteo/torchcuda/lib/python3.12/site-packages/pytorch_lightning/trainer/trainer.py", line 599, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/matteo/torchcuda/lib/python3.12/site-packages/pytorch_lightning/trainer/trainer.py", line 1012, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/home/matteo/torchcuda/lib/python3.12/site-packages/pytorch_lightning/trainer/trainer.py", line 1056, in _run_stage
    self.fit_loop.run()
  File "/home/matteo/torchcuda/lib/python3.12/site-packages/pytorch_lightning/loops/fit_loop.py", line 216, in run
    self.advance()
  File "/home/matteo/torchcuda/lib/python3.12/site-packages/pytorch_lightning/loops/fit_loop.py", line 455, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/home/matteo/torchcuda/lib/python3.12/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 150, in run
    self.advance(data_fetcher)
  File "/home/matteo/torchcuda/lib/python3.12/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 282, in advance
    batch, _, __ = next(data_fetcher)
                   ^^^^^^^^^^^^^^^^^^
  File "/home/matteo/torchcuda/lib/python3.12/site-packages/pytorch_lightning/loops/fetchers.py", line 134, in __next__
    batch = super().__next__()
            ^^^^^^^^^^^^^^^^^^
  File "/home/matteo/torchcuda/lib/python3.12/site-packages/pytorch_lightning/loops/fetchers.py", line 61, in __next__
    batch = next(self.iterator)
            ^^^^^^^^^^^^^^^^^^^
  File "/home/matteo/torchcuda/lib/python3.12/site-packages/pytorch_lightning/utilities/combined_loader.py", line 341, in __next__
    out = next(self._iterator)
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/matteo/torchcuda/lib/python3.12/site-packages/pytorch_lightning/utilities/combined_loader.py", line 78, in __next__
    out[i] = next(self.iterators[i])
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matteo/torchcuda/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 733, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/matteo/torchcuda/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1515, in _next_data
    return self._process_data(data, worker_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matteo/torchcuda/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1550, in _process_data
    data.reraise()
  File "/home/matteo/torchcuda/lib/python3.12/site-packages/torch/_utils.py", line 750, in reraise
    raise exception
OSError: Caught OSError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/matteo/torchcuda/lib/python3.12/site-packages/torch/utils/data/_utils/worker.py", line 349, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/matteo/torchcuda/lib/python3.12/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/home/matteo/torchcuda/lib/python3.12/site-packages/torch_atlas_ds/atlas.py", line 339, in __getitem__
    return self.shards[shard_idx][within_shard_index]
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/home/matteo/torchcuda/lib/python3.12/site-packages/torch_atlas_ds/atlas.py", line 211, in __getitem__
    self._lazy_init()
  File "/home/matteo/torchcuda/lib/python3.12/site-packages/torch_atlas_ds/atlas.py", line 173, in _lazy_init
    self.block_index = np.load(self.root / 'index.npy', mmap_mode='r' if self.mmap_index else None)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matteo/torchcuda/lib/python3.12/site-packages/numpy/lib/npyio.py", line 453, in load
    return format.open_memmap(file, mode=mmap_mode,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matteo/torchcuda/lib/python3.12/site-packages/numpy/lib/format.py", line 924, in open_memmap
    with open(os_fspath(filename), 'rb') as fp:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 24] Too many open files: '../matformer_norepo/liberliber1024/15495/index.npy'
